# Site settings
title: Student Portfolio
description: A short portfolio for Timothy
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Timothy Robinson
user_description: A software technology student studying at Macquarie University
user_title: Software Technology student
email: Timothy.Robinson123@gmail.com
github_username:  timrob0

# Google-analytics
#google-analytics:
#  id: ""

#exclude: ['package.json', 'src' , 'node_modules']
